feat: add matchGlob parameter to list_blobs
googleapis/python-storage pull request #1055
Opened 2023-05-26 20:55 UTC by cojenco

Fixes #1035

2023-06-08 21:55 UTC, JesseLovelace approved these changes

2023-06-08 23:28 UTC, andrewsg requested changes

2023-06-09 18:36 UTC, cojenco commented on google/cloud/storage/bucket.py
> +        match_glob=None,
Good call out, thank you! I've moved the parameter, PTAL

2023-06-14 16:38 UTC, andrewsg approved these changes

2023-06-14 21:16 UTC, merged