chore: Amend Transfer Manager samples
googleapis/python-storage pull request #1113
Opened 2023-08-29 23:31 UTC by andrewsg

2023-08-30 23:33 UTC, cojenco requested changes

2023-08-31 17:35 UTC, andrewsg commented on samples/snippets/storage_transfer_manager_download_many.py
> +
Good catch, thank you!

2023-08-31 17:41 UTC, andrewsg commented
PTAL

2023-08-31 18:27 UTC, cojenco approved these changes

2023-08-31 18:27 UTC, cojenco commented on samples/snippets/storage_transfer_manager_download_bucket.py
> +# Copyright 2022 Google LLC
```suggestion
# Copyright 2023 Google LLC
```

2023-08-31 20:09 UTC, merged