fix: from_string method of blob and bucket class
googleapis/python-storage pull request #290
Opened 2020-10-08 12:43 UTC by HemangChothani

Fixes #286

2020-10-08 17:57 UTC, tseaver requested changes
Rather than changing the signature of `Blob.from_string`, the fix should be to change `Blob._do_multipart_upload` (and likewise `Blob._initiate_resumable_upload`) to use the passed-in client. The caller (`Blob._do_upload`) should likewise call `self._require_client` to use its own `_client` attribute as a fallback for when no explicit `client` is passed in.

2020-10-08 17:57 UTC, tseaver commented on google/cloud/storage/blob.py
> +    def from_string(cls, uri, client):
Making a formerly optional argument required is a breaking change.

2020-10-09 14:32 UTC, tseaver requested changes

2020-10-09 14:32 UTC, tseaver commented on tests/unit/test_blob.py
>              )
Given that the passed-in `client` is not used by `Blob._do_multipart_upload` before the `ValueError` is raised, this change is unnecessary / distracting.

We do need extra test cases that verify that the passed-in `client` is used in preference to `self._client` in both `Blob._do_multipart_upload` and `Blob._initiate_resumable_upload`.

2020-10-29 04:37 UTC, HemangChothani commented
@tseaver PTAL!

2020-11-11 20:05 UTC, tseaver approved these changes

2020-11-11 20:20 UTC, merged