feat: Add encryption_key param to Blob.from_string
googleapis/python-storage pull request #391
Opened 2021-03-09 02:30 UTC by harrydrippin

This PR contains several fixes as follows:

* Add `encryption_key` parameter to Blob.from_string.
* Fix several typos and format errors.

Fixes #390 🦕

2021-04-05 23:15 UTC, cojenco commented on tests/unit/test_blob.py
> +        encryption_key = "0123456789abcdef0123456789abcdef"
```suggestion
        encryption_key = b"0123456789abcdef0123456789abcdef"
```

2021-04-05 23:33 UTC, cojenco commented on google/cloud/storage/blob.py
>           :type uri: str
Thanks for catching this. For the doc string, the indentation should be left-indented instead and aligned with the triple quotes. Please help fix, thanks!

2021-04-05 23:48 UTC, cojenco requested changes
Thanks @harrydrippin for submitting a PR and helping us improve. Please refer to the comments for a few change requests. Feel free to let me know if any questions. Thank you!

2021-04-20 18:01 UTC, tseaver approved these changes

2021-04-20 18:02 UTC, closed without merging

2021-04-20 18:05 UTC, tseaver commented
@harrydrippin Thanks for your patch.  We've decided to use a getter/setter for encryption key: https://github.com/googleapis/python-storage/pull/409.