chore: generate python samples templates in owlbot.py
googleapis/python-storage pull request #539
Opened 2021-08-17 20:49 UTC by busunkim96

Generate python samples templates in owlbot.py

2021-08-17 21:10 UTC, tseaver requested changes

2021-08-17 21:10 UTC, tseaver commented on owlbot.py
> +python.py_samples(skip_readmes=True)
Syntax error.

2021-08-18 13:27 UTC, parthea approved these changes

2021-08-18 13:28 UTC, parthea approved these changes

2021-08-18 15:42 UTC, parthea commented on owlbot.py
> +python.py_samples(skip_readmes=True)
Good catch!

2021-08-18 16:01 UTC, tseaver commented
Flaky systest reported in #541.  Re-running.

2021-08-18 16:01 UTC, tseaver approved these changes

2021-08-18 16:27 UTC, merged