fix: do not append duplicates to user agent string
googleapis/python-storage pull request #570
Opened 2021-09-01 17:29 UTC by ddelgrosso1

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #565 🦕

2021-09-01 18:42 UTC, tseaver requested changes
@ddelgrosso1 Can you please add a unit test which reproduces the issue (i.e., failing with this change not applied, but passing with it applied)?

2021-09-01 18:42 UTC, tseaver commented on google/cloud/storage/_http.py
> +            self._client_info.user_agent += " gcloud-python/{} ".format(__version__)
```suggestion
        agent_version = "gcloud-python/{}".format(__version__)
        if  agent_version not in self._client_info.user_agent:
            self._client_info.user_agent += " {} ".format(agent_version)
```

2021-09-01 20:24 UTC, tseaver commented
@gooblebot I consent.

2021-09-01 20:27 UTC, tseaver commented
@ddelgrosso1 The `lint` session is failing, likely to do with something in the suggestion you merged.  Can you pull from here to your local branch and run `nox -s blacken` and commit / push the resulting change?

2021-09-01 21:14 UTC, andrewsg commented
Denis, please ping me if you would like help running the auto-formatter/linter and writing the regression test.

2021-09-02 17:23 UTC, tseaver approved these changes
@ddelgrosso1 Thanks for the test!  I verified that it fails against `main` without the patch.

2021-09-02 17:34 UTC, merged