feat!: Remove Python 2 support
googleapis/python-storage pull request #657
Opened 2021-11-22 23:14 UTC by andrewsg

BREAKING CHANGE: This PR removes Python 2 support in the setup.py metadata, test runner and code itself. This is intended to be released as a major version update. Python 2 users can continue to use the 1.x version of the client library.

2021-11-26 19:12 UTC, tseaver requested changes

2021-11-26 19:12 UTC, tseaver commented on google/cloud/storage/_signing.py
> +import http
Prefer to import the explicit submodule:
```suggestion
import http.client
```

Also, sort w/ stdlib imports.

2021-11-26 19:12 UTC, tseaver commented on google/cloud/storage/batch.py
> +        super_init(payload, "http", encode_noop)
For Python3-only, `super()` is nice:
```suggestion
        super()__init__(payload, "http", encode_noop)
```

2021-11-26 19:12 UTC, tseaver commented on google/cloud/storage/_helpers.py
> +from urllib.parse import urlsplit
Sort w/ stdlib imports.

2021-11-26 19:12 UTC, tseaver commented on google/cloud/storage/blob.py
> +from urllib.parse import urlunsplit
Sort w/ stdlib imports.

2021-11-26 19:12 UTC, tseaver commented on google/cloud/storage/bucket.py
> +from urllib.parse import urlsplit
Sort w/ stdlib imports.

2021-11-26 19:12 UTC, tseaver commented on tests/unit/test__signing.py
> +import urllib.parse
Sort w/ stdlib imports.

2021-11-26 19:12 UTC, tseaver commented on tests/unit/test_batch.py
> +from http.client import NO_CONTENT
Sort w/ stdlib imports.

2021-11-26 19:12 UTC, tseaver commented on tests/unit/test_blob.py
> +import http.client
Sort under `hashlib`

2021-11-26 19:12 UTC, tseaver commented on tests/unit/test_client.py
> +import http.client
Sort below `base64`

2021-11-26 19:14 UTC, tseaver commented
@andrewsg The `Kokoro system-2.7` job is configured both in the `.kokoro/presubmit/system-2.7.cfg` file and in `google3`.

2022-01-07 22:42 UTC, andrewsg commented
@tseaver This was on hold due to the release freeze last month. Thank you as always for your thorough review. PTAL. Will address google3 issue shortly.

2022-01-11 22:05 UTC, cojenco commented on README.rst
> +``google-cloud-storage 1.43.0``, released 2021-11-17.
```suggestion
``google-cloud-storage 1.44.0``, released 2022-01-05.
```

2022-01-11 22:20 UTC, Breathtender commented
So happy to see all the clean up. Nothing else to add beyond the requests that tres and cathy made; lgtm. Is there a change that should be made in here for kokoro to not try and still run the system-2.7 tests?

2022-01-12 04:22 UTC, cojenco reviewed
LGTM🎉🎉 Thanks Andrew for getting us across the finish line!

2022-01-12 17:44 UTC, cojenco approved these changes

2022-01-12 17:59 UTC, tseaver approved these changes

2022-01-12 18:12 UTC, merged