chore: add internal benchmarking script
googleapis/python-storage pull request #760
Opened 2022-04-08 18:44 UTC by cojenco

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-04-12 23:40 UTC, frankyn requested changes

2022-04-13 00:15 UTC, cojenco commented on tests/perf/benchmarking.py
> +    payload = _create_block(size)
Updated to upload from disk using NamedTemporaryFile

2022-04-13 00:16 UTC, cojenco commented on tests/perf/benchmarking.py
> +    checksum = kwargs.get("checksum")
yep missed that, thanks!

2022-04-13 00:17 UTC, cojenco commented on tests/perf/benchmarking.py
> +    res["Crc32cEnabled"] = func.keywords.get("Crc32cEnabled")
makes sense, updated!

2022-04-13 19:16 UTC, cojenco commented on tests/perf/benchmarking.py
> +    payload = _create_block(size)
Changed to download to file as well

2022-04-13 19:16 UTC, cojenco commented on tests/perf/benchmarking.py
> +    idx_checksum = random.randrange(0, 2)
done

2022-04-13 19:19 UTC, cojenco commented on tests/perf/benchmarking.py
> +        "LibBufferSize": 104857600,
`LibBufferSize` is the library default of 100 MiB. Added a constant `DEFAULT_LIB_BUFFER_SIZE` along with a link to docs.

`AppBufferSize` is not supported here, updated!

2022-04-13 22:35 UTC, cojenco commented on tests/perf/benchmarking.py
> +    pool_output = p.map(main_profiling, range(1))
Good catch. I've updated to set number of samples as the iterable in `map` so we're running on multiple processes concurrently. Let me know what other ways can be done.

2022-04-14 05:25 UTC, frankyn requested changes

2022-04-14 21:04 UTC, cojenco commented on tests/perf/benchmarking.py
> +CSV_PATH = args.o
Done, also added a `main()` to run the `benchmarker_runner` and output csv file

2022-04-15 20:50 UTC, Breathtender approved these changes
Wow Cathy, this has become really beautifully polished and put together! Thanks so much for continuing to evolve on our initial work together and bringing it to such a well done finished piece!

LGTM

2022-04-15 20:50 UTC, Breathtender commented on tests/perf/README.md
> +$ python3 benchmarking.py --num_samples 10000 --max_size 16384
Oooh love the configurability you got in here!

2022-05-09 21:16 UTC, frankyn approved these changes

2022-05-10 21:53 UTC, merged