Remove the dependency on the separate package mock.
googleapis/python-storage pull request #770
Opened 2022-04-16 10:13 UTC by mcepl

unittest.mock in the standard library works as well.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #769

2022-04-18 18:20 UTC, kurtisvg approved these changes

2022-04-20 20:25 UTC, tritone approved these changes

2022-04-20 22:15 UTC, tritone requested changes
Actually, looking at the CI, I see multiple test failures that indicate that these aren't 100% equivalent. If you'd like to try running the tests and fixing up, you're welcome to, but otherwise I'll have to close this PR.

2022-04-21 08:22 UTC, mcepl commented
> Actually, looking at the CI, I see multiple test failures that indicate that these aren't 100% equivalent. If you'd like to try running the tests and fixing up, you're welcome to, but otherwise I'll have to close this PR.

You are right, it is more bother than gain. This repository apparently (as usual for Google projects) depends on the secret sauce (there is no `noxfile.py` anywhere in the repository), so I have no chance to fix it properly anyway.

2022-04-21 08:22 UTC, closed without merging